# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: dolphinnext-trnaseq-1.0
channels:
   - conda-forge
   - bioconda
   - defaults
   - mamba
dependencies:
   - python=3.7
   - mimseq=0.3.3.4
   - umi_tools=1.1.1
   - trimmomatic=0.39
   - fastqc=0.11.8
   - fastx_toolkit=0.0.14
   